name: luoxiaohei
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  go_router: ^6.5.5
  flutter_riverpod: ^2.1.1
  riverpod_annotation: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0

flutter:
  uses-material-design: true
